const Head = () => (
    <>
        <title>ESLint, Prettier and Husky</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/emblem_logo.png" />
    </>
);

export default Head;
